[package]
name = "mqtt"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "syncpubsub"
path = "src/syncpubsub.rs"

[[bin]]
name = "asyncpubsub"
path = "src/asyncpubsub.rs"


[dependencies]
rumqttc = "0.24.0"
pretty_env_logger = "0.4"
tokio = { version = "1", features = ["full"] }
